#! python3

import os
import openpyxl
import time
start_time = time.time()

os.chdir('c:\\users\\alex_\\Desktop')

wb = openpyxl.Workbook()
sheet = wb['Sheet']
sheet.title = 'All'

sheet['A1'] = 'Song Title'
sheet['B1'] = 'Song Size'
sheet['C1'] = 'Song Path'

#workingFolder = 'D:\\music\\muzica alex'
workingFolder = 'testFolder'

line = 2

for folderName, subfolders, filenames in os.walk(workingFolder):
    for item in filenames:
        itemPath = os.path.join(folderName +'\\')
        itemSize = str(os.stat(os.path.join(folderName +'\\'+ item)).st_size)
        name = sheet.cell(row = line, column = 1, value = item)
        size = sheet.cell(row = line, column = 2, value = itemSize)
        path = sheet.cell(row = line, column = 3, value = itemPath)
        line += 1

wb.save('SongListTest.xlsx')

# create a new sheet, for both duplicates (same name, same size)
bothDuplicates = wb.create_sheet("Duplicates")
bothDuplicates['A1'] = 'Song Title'
bothDuplicates['B1'] = 'Song Size'
bothDuplicates['C1'] = 'Initial Song Path'
bothDuplicates['D1'] = 'Duplicate Song Path'
dupLine = 2
# create a new sheet, for same name
nameDuplicates = wb.create_sheet("Name Duplicates")
nameDuplicates['A1'] = 'Song Title'
nameDuplicates['B1'] = 'Song Size'
nameDuplicates['C1'] = 'Initial Song Path'
nameDuplicates['D1'] = 'Duplicate Song Path'
nameLine = 2
# create a new sheet, for same size
sizeDuplicates = wb.create_sheet("Size Duplicates")
sizeDuplicates['A1'] = 'Song Title'
sizeDuplicates['B1'] = 'Song Size'
sizeDuplicates['C1'] = 'Initial Song Path'
sizeDuplicates['D1'] = 'Duplicate Song Path'
sizeLine = 2

# definition of copy function from one sheet to another, by lines
def copyLine(sourceSheet, sourceLine, initial, destinationSheet, destinationLine):
    for i in range (1, 3):
        destinationSheet.cell(row = destinationLine, column = i).value = sourceSheet.cell(row = sourceLine, column = i).value
    destinationSheet.cell(row = destinationLine, column = 3).value = sourceSheet.cell(row = initial, column = 3).value
    destinationSheet.cell(row = destinationLine, column = 4).value = sourceSheet.cell(row = sourceLine, column = 3).value

# loop through sheet All to find duplicates
for counter in range (2, line):
    for content in range (counter+1, line):
        if(sheet.cell(row = counter, column = 1).value == sheet.cell(row = content, column = 1).value):
            if(sheet.cell(row = counter, column = 2).value == sheet.cell(row = content, column = 2).value):
                # copy contents from the content line to clearDuplicates dupLine and increment dupLine
                copyLine(sheet, content, counter, bothDuplicates, dupLine)
                dupLine += 1
            # copy contents from the content line to nameDuplicates nameLine and increment nameLine
            copyLine(sheet, content, counter, nameDuplicates, nameLine)
            nameLine += 1
        elif(sheet.cell(row = counter, column = 2).value == sheet.cell(row = content, column = 2).value):
            # copy contents from the content line to sizeDuplicates sizeLine and increment sizeLine
            copyLine(sheet, content, counter, sizeDuplicates, sizeLine)
            sizeLine += 1

wb.save('SongListTest.xlsx')

inputFile = open('C:\\Users\\alex_\\Desktop\\info.txt', 'w')
# for i in range (2,line):
    # inputFile.write('\nSong:\n' + sheet.cell(row = i, column = 1).value +
                    # '\nSize:\n' + sheet.cell(row = i, column = 2).value +
                    # '\nPath:\n' + sheet.cell(row = i, column = 3).value + '\n')
inputFile.write("--- %s seconds ---" % (time.time() - start_time))
inputFile.close()
